# Generated by Django 5.0.14 on 2026-06-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Selected', max_length=20)),
                ('package_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Package offered in LPA', max_digits=10, null=True)),
                ('selection_date', models.DateField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_result', to='core.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='core.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='core.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_results', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Placement Results',
                'ordering': ['-selection_date'],
                'unique_together': {('student', 'application')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_posted', 'New Job Posted'), ('shortlisted', 'Application Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Application Rejected'), ('selected', 'Placement Selected'), ('result_published', 'Result Published')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.application')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.student')),
                ('placement_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.placementresult')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
