# Generated by Django 5.0.14 on 2026-06-18 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placementresult_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placementresult',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Result has been published and is now final'),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Result has been revoked'),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Admin who published this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='revocation_reason',
            field=models.TextField(blank=True, help_text='Reason for revoking the result'),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who revoked this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='revoked_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when result was revoked', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_posted', 'New Job Posted'), ('shortlisted', 'Application Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Application Rejected'), ('selected', 'Placement Selected'), ('result_published', 'Result Published'), ('result_revoked', 'Result Revoked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placementresult',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when result was published'),
        ),
        migrations.AlterField(
            model_name='placementresult',
            name='selection_date',
            field=models.DateField(help_text="Auto-set to today's date when result is published"),
        ),
        migrations.AddIndex(
            model_name='placementresult',
            index=models.Index(fields=['is_published', 'is_revoked'], name='core_placem_is_publ_091165_idx'),
        ),
        migrations.AddIndex(
            model_name='placementresult',
            index=models.Index(fields=['student', 'is_published'], name='core_placem_student_c9fa8f_idx'),
        ),
    ]
