# Generated by Django 5.0.14 on 2026-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placementresult_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Selected', 'Selected'), ('Waiting List', 'Waiting List'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_posted', 'New Job Posted'), ('application_submitted', 'Application Submitted'), ('shortlisted', 'Application Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('waiting_list', 'Waiting List'), ('rejected', 'Application Rejected'), ('selected', 'Placement Selected'), ('result_published', 'Result Published'), ('result_revoked', 'Result Revoked')], max_length=25),
        ),
    ]
